/**
 * @solvinghealth/identity — Identity Management
 *
 * Open source identity primitives for healthcare: NPI validation,
 * ComfortCard digital identity, W3C DID, Remote Online Notarization,
 * WorkOS AuthKit integration, ABAC policy engine, and audit logging.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// NPI Identity
export {
  type CredentialStatus,
  CredentialStatusSchema,
  type CredentialTier,
  CredentialTierSchema,
  CREDENTIAL_TIERS,
  type NPIProfile,
  NPIProfileSchema,
  type NPIType,
  NPITypeSchema,
  type ProviderTaxonomy,
  ProviderTaxonomySchema,
  type StateLicense,
  StateLicenseSchema,
  buildNPPESLookupUrl,
  buildNPPESSearchUrl,
  determineCredentialTier,
  getNPIType,
  parseNPPESResponse,
  validateNPI,
} from './npi.js';

// ComfortCard
export {
  type AccessTier,
  AccessTierSchema,
  type AppleWalletPass,
  AppleWalletPassSchema,
  type CardBadge,
  CardBadgeSchema,
  type ComfortCard,
  ComfortCardSchema,
  type EmergencyInfo,
  EmergencyInfoSchema,
  type QRPayload,
  QRPayloadSchema,
  createComfortCard,
  generateAppleWalletPass,
  generateGooglePayPass,
  generateQRPayload,
  getAccessibleData,
  verifyQRPayload,
} from './comfortcard.js';

// Decentralized Identity (DID)
export {
  type CredentialSubject,
  CredentialSubjectSchema,
  type CredentialType,
  CredentialTypeSchema,
  type DIDDocument,
  DIDDocumentSchema,
  type DIDMethod,
  DIDMethodSchema,
  type ServiceEndpoint,
  ServiceEndpointSchema,
  type VerifiableCredential,
  VerifiableCredentialSchema,
  type VerificationMethod,
  VerificationMethodSchema,
  type VerificationResult,
  VerificationResultSchema,
  anchorToBaseL2,
  createCaregiverDID,
  createDIDDocument,
  createPatientDID,
  createPhysicianDID,
  issueCaregiverCredential,
  issueCredential,
  issuePhysicianCredential,
  verifyCredential,
} from './did.js';

// Remote Online Notarization
export {
  type DocumentType,
  DocumentTypeSchema,
  type FaceMatchResult,
  FaceMatchResultSchema,
  type IDDocumentType,
  IDDocumentTypeSchema,
  type IDVerificationResult,
  IDVerificationResultSchema,
  type RONDocument,
  RONDocumentSchema,
  type RONSession,
  RONSessionSchema,
  type RONSessionStatus,
  RONSessionStatusSchema,
  type StateRegistrySubmission,
  StateRegistrySubmissionSchema,
  RON_ELIGIBLE_STATES,
  createRONSession,
  generateRegistrySubmission,
  getRONRequirements,
  isRONEligible,
  packageAdvanceDirectives,
  recordFaceMatch,
  recordIDVerification,
} from './ron.js';

// WorkOS AuthKit Integration
export {
  type WorkOSConfig,
  type SolvingHealthRole,
  type WorkOSUser,
  type WorkOSSession,
  type AuthorizationUrlOptions,
  type CallbackResult,
  type RedactionLevel,
  type AccessDecision,
  type RoleMappingEntry,
  type WorkOSOrganizationId,
  type OrganizationMember,
  WorkOSConfigSchema,
  WorkOSUserSchema,
  WorkOSSessionSchema,
  AccessDecisionSchema,
  SolvingHealthRoleSchema,
  WORKOS_ORGANIZATIONS,
  getWorkOSClient,
  getAuthorizationUrl,
  handleCallback,
  getUserProfile,
  createUser,
  listOrganizationMembers,
  refreshSession,
  mapWorkOSRole,
} from './workos.js';

// Attribute-Based Access Control (ABAC)
export {
  type ResourceDescriptor,
  type ResourceSensitivity,
  type Action,
  type AccessContext,
  type Obligation,
  type PolicyDecisionConfig,
  type AbacMiddlewareConfig,
  ResourceSensitivitySchema,
  ActionSchema,
  ResourceDescriptorSchema,
  AccessContextSchema,
  ObligationSchema,
  PolicyDecisionEngine,
  canAccess,
  abacMiddleware,
} from './abac.js';

// WorkOS Audit Log Events
export {
  type AuditEventType,
  type AuditActor,
  type AuditTarget,
  type AuditEvent,
  type AuditEmitterConfig,
  AUDIT_EVENT_TYPES,
  AuditActorSchema,
  AuditTargetSchema,
  AuditEventSchema,
  buildActor,
  buildSystemActor,
  buildTarget,
  createAuditEvent,
  createAuditEvents,
  phiAccessEvent,
  lmnEvent,
  encounterEvent,
  complianceEvent,
} from './audit-events.js';
